name: build-ma-json
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4 lxml
      - name: Build JSON
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          SEC_USER_AGENT: ${{ secrets.SEC_USER_AGENT }}
          OUT_PATH: data/ma_enriched.json
        run: python scripts/build_ma_json.py
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add portfolio/data/ma_enriched.json
          git diff --quiet && echo "No changes" || git commit -m "update deals"
          git push